//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, SYSLIB0011,SYSLIB0032
// dnlib: See LICENSE.txt for more info

namespace DatadogTestLogger.Vendors.Datadog.Trace.Vendors.dnlib.DotNet.Emit {
	/// <summary>
	/// CIL opcode flow control
	/// </summary>
	internal enum FlowControl {
		/// <summary/>
		Branch,
		/// <summary/>
		Break,
		/// <summary/>
		Call,
		/// <summary/>
		Cond_Branch,
		/// <summary/>
		Meta,
		/// <summary/>
		Next,
		/// <summary/>
		Phi,
		/// <summary/>
		Return,
		/// <summary/>
		Throw,
	}
}
