//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
namespace DatadogCollector.Vendors.Mono.Cecil
{
    internal enum TypeComparisonMode {
        Exact,
        SignatureOnly,

        /// <summary>
        /// Types can be in different assemblies, as long as the module, assembly, and type names match they will be considered equal
        /// </summary>
        SignatureOnlyLoose
    }
}
