//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="LoggerIntegrationCommon.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;
using Datadog.Trace.Vendors.Datadog.Trace.Configuration;

namespace Datadog.Trace.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.ILogger
{
    internal static class LoggerIntegrationCommon
    {
        public const string IntegrationName = nameof(Configuration.IntegrationId.ILogger);
        private const IntegrationId IntegrationId = Configuration.IntegrationId.ILogger;

        private static readonly DatadogLoggingScope DatadogScope = new();

        public static void AddScope<TAction, TState>(Tracer tracer, TAction callback, TState state)
        {
            if (tracer.Settings.LogsInjectionEnabled
             && tracer.Settings.IsIntegrationEnabled(IntegrationId)
             && callback is Action<object, TState> foreachCallback)
            {
                foreachCallback.Invoke(DatadogScope, state);
            }
        }
    }
}
