//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace DatadogTestLogger.Vendors.Datadog.Trace.Vendors.StatsdClient.Utils
{
    internal interface IPool
    {
        void Enqueue(object obj);
    }
}