//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="FilterList.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;
using DatadogTestLogger.Vendors.Datadog.Trace.Debugger.Helpers;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Debugger.Configurations.Models
{
    internal class FilterList : IEquatable<FilterList>
    {
        public string[] PackagePrefixes { get; set; }

        public string[] Classes { get; set; }

        public bool Equals(FilterList other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return PackagePrefixes.NullableSequentialEquals(other.PackagePrefixes) && Classes.NullableSequentialEquals(other.Classes);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (obj.GetType() != this.GetType())
            {
                return false;
            }

            return Equals((FilterList)obj);
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(PackagePrefixes, Classes);
        }
    }
}
