//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="Diagnostics.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;
using DatadogTestLogger.Vendors.Datadog.Trace.Vendors.Newtonsoft.Json;
using DatadogTestLogger.Vendors.Datadog.Trace.Vendors.Newtonsoft.Json.Converters;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Debugger.Sink.Models
{
    internal record Diagnostics
    {
        public Diagnostics(string probeId, Status status)
        {
            ProbeId = probeId;
            Status = status;
        }

        [JsonProperty("probeId")]
        public string ProbeId { get; }

        [JsonProperty("status")]
        public Status Status { get; }

        [JsonProperty("exception")]
        public ProbeException Exception { get; private set; }

        public void SetException(Exception exception, string errorMessage)
        {
            Exception = new ProbeException();

            if (exception != null)
            {
                Exception = new ProbeException()
                {
                    Type = exception.GetType().Name,
                    Message = exception.Message,
                    StackTrace = exception.StackTrace
                };
            }

            if (!string.IsNullOrWhiteSpace(errorMessage))
            {
                Exception.Type ??= "NO_TYPE";
                Exception.Message = errorMessage;
            }
        }
    }
}
