//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="RabbitMQHeadersCollectionAdapter.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>
#nullable enable

using System;
using System.Collections.Generic;
using DatadogTestLogger.Vendors.Datadog.Trace.Headers;

namespace DatadogTestLogger.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.RabbitMQ
{
    internal readonly struct RabbitMQHeadersCollectionAdapter : IBinaryHeadersCollection
    {
        private readonly IDictionary<string, object> _headers;

        public RabbitMQHeadersCollectionAdapter(IDictionary<string, object> headers)
        {
            _headers = headers;
        }

        public byte[] TryGetLastBytes(string name)
        {
            if (_headers.TryGetValue(name, out var value) && value is byte[] bytes)
            {
                return bytes;
            }

            return Array.Empty<byte>();
        }

        public void Add(string name, byte[] value)
        {
            _headers[name] = value;
        }
    }
}
