//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
using Datadog.Trace.Vendors.Datadog.Trace.Vendors.Serilog.Events;

namespace Datadog.Trace.Vendors.Datadog.Trace.Vendors.Serilog.Core
{
    /// <summary>
    /// Supports the policy-driven construction of <see cref="LogEventPropertyValue"/>s given
    /// regular .NET objects.
    /// </summary>
    internal interface ILogEventPropertyValueFactory
    {
        /// <summary>
        /// Create a <see cref="LogEventPropertyValue"/> given a .NET object and destructuring
        /// strategy.
        /// </summary>
        /// <param name="value">The value of the property.</param>
        /// <param name="destructureObjects">If true, and the value is a non-primitive, non-array type,
        /// then the value will be converted to a structure; otherwise, unknown types will
        /// be converted to scalars, which are generally stored as strings.</param>
        /// <returns>The value.</returns>
        LogEventPropertyValue CreatePropertyValue(object value, bool destructureObjects = false);
    }
}
