//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
//
// Author:
//   Jb Evain (jbevain@gmail.com)
//
// Copyright (c) 2008 - 2015 Jb Evain
// Copyright (c) 2008 - 2011 Novell, Inc.
//
// Licensed under the MIT/X11 license.
//

using DatadogTestLogger.Vendors.Mono.Cecil.PE;

using RID = System.UInt32;

namespace DatadogTestLogger.Vendors.Mono.Cecil.Metadata {

	sealed class PdbHeap : Heap {

		public byte [] Id;
		public RID EntryPoint;
		public long TypeSystemTables;
		public uint [] TypeSystemTableRows;

		public PdbHeap (byte [] data)
			: base (data)
		{
		}

		public bool HasTable (Table table)
		{
			return (TypeSystemTables & (1L << (int) table)) != 0;
		}
	}
}
