//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="TestSuiteVisibilityTags.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>
#nullable enable

namespace DatadogTestLogger.Vendors.Datadog.Trace.Ci.Tags;

internal static class TestSuiteVisibilityTags
{
    /// <summary>
    /// Test session id
    /// </summary>
    public const string TestSessionId = "test_session_id";

    /// <summary>
    /// Test module id
    /// </summary>
    public const string TestModuleId = "test_module_id";

    /// <summary>
    /// Test suite id
    /// </summary>
    public const string TestSuiteId = "test_suite_id";

    /// <summary>
    /// Test session command environment variable
    /// </summary>
    public const string TestSessionCommandEnvironmentVariable = "DD_TESTSESSION_COMMAND";

    /// <summary>
    /// Test session working directory environment variable
    /// </summary>
    public const string TestSessionWorkingDirectoryEnvironmentVariable = "DD_TESTSESSION_WORKINGDIRECTORY";
}
