//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="RcmClient.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System.Collections.Generic;
using DatadogTestLogger.Vendors.Datadog.Trace.Vendors.Newtonsoft.Json;

namespace DatadogTestLogger.Vendors.Datadog.Trace.RemoteConfigurationManagement.Protocol
{
    internal class RcmClient
    {
        public RcmClient(string id, ICollection<string> products, RcmClientTracer clientTracer, RcmClientState state, byte[] capabilities)
        {
            Id = id;
            Products = products;
            IsTracer = true;
            ClientTracer = clientTracer;
            State = state;
            Capabilities = capabilities;
        }

        [JsonProperty("state")]
        public RcmClientState State { get; }

        [JsonProperty("id")]
        public string Id { get; }

        [JsonProperty("products")]
        public ICollection<string> Products { get; }

        [JsonProperty("is_tracer")]
        public bool IsTracer { get; }

        [JsonProperty("client_tracer")]
        public RcmClientTracer ClientTracer { get; }

        [JsonProperty("capabilities")]
        public byte[] Capabilities { get; }
    }
}
