//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="ProbeData.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;
using System.Reflection;
using DatadogTestLogger.Vendors.Datadog.Trace.Debugger.Expressions;
using DatadogTestLogger.Vendors.Datadog.Trace.Debugger.Helpers;
using DatadogTestLogger.Vendors.Datadog.Trace.Debugger.RateLimiting;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Debugger.Instrumentation.Collections
{
    /// <summary>
    /// Holds data needed during Debugger instrumentation execution.
    /// </summary>
    internal readonly record struct ProbeData(string ProbeId, AdaptiveSampler Sampler, ProbeProcessor Processor)
    {
        internal static ProbeData Empty = new(string.Empty, null, null);

        public string ProbeId { get; } = ProbeId;

        public AdaptiveSampler Sampler { get; } = Sampler;

        public ProbeProcessor Processor { get; } = Processor;

        public bool IsEmpty() => this == Empty;
    }
}
