//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace DatadogTestLogger.Vendors.Datadog.Trace.Vendors.StatsdClient.Bufferize
{
    internal interface IBufferBuilderHandler
    {
        void Handle(byte[] buffer, int length);
    }
}