//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="HttpHeaderHelperBase.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System.IO;
using System.Threading.Tasks;

namespace DatadogTestLogger.Vendors.Datadog.Trace.HttpOverStreams
{
    internal abstract class HttpHeaderHelperBase
    {
        protected abstract string MetadataHeaders { get; }

        protected abstract string ContentType { get; }

        public Task WriteLeadingHeaders(HttpRequest request, TextWriter writer)
        {
            var leadingHeaders =
                $"{request.Verb} {request.Path} HTTP/1.1{DatadogHttpValues.CrLf}Host: {request.Host}{DatadogHttpValues.CrLf}Accept-Encoding: identity{DatadogHttpValues.CrLf}Content-Length: {request.Content?.Length ?? 0}{DatadogHttpValues.CrLf}{MetadataHeaders}";
            return writer.WriteAsync(leadingHeaders);
        }

        public Task WriteHeader(TextWriter writer, HttpHeaders.HttpHeader header)
        {
            return writer.WriteAsync($"{header.Name}: {header.Value}{DatadogHttpValues.CrLf}");
        }
    }
}
