//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="ElasticsearchV5Constants.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using Datadog.Trace.Vendors.Datadog.Trace.Configuration;

namespace Datadog.Trace.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V5
{
    internal static class ElasticsearchV5Constants
    {
        internal const string Version5 = "5";
        internal const string ElasticsearchAssemblyName = "Elasticsearch.Net";
        internal const string RequestPipelineTypeName = "Elasticsearch.Net.RequestPipeline";

        internal const string IntegrationName = nameof(Configuration.IntegrationId.ElasticsearchNet);
        internal const IntegrationId IntegrationId = Configuration.IntegrationId.ElasticsearchNet;
    }
}
