//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="NameValueConfigurationSource.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

#nullable enable

using System.Collections.Specialized;
using DatadogTestLogger.Vendors.Datadog.Trace.Configuration.Telemetry;
using DatadogTestLogger.Vendors.Datadog.Trace.SourceGenerators;
using DatadogTestLogger.Vendors.Datadog.Trace.Telemetry;
using DatadogTestLogger.Vendors.Datadog.Trace.Telemetry.Metrics;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Configuration
{
    /// <summary>
    /// Represents a configuration source that retrieves
    /// values from the provided <see cref="NameValueCollection"/>.
    /// </summary>
    internal class NameValueConfigurationSource : StringConfigurationSource
    {
        private readonly NameValueCollection _nameValueCollection;

        /// <summary>
        /// Initializes a new instance of the <see cref="NameValueConfigurationSource"/> class
        /// that wraps the specified <see cref="NameValueCollection"/>.
        /// </summary>
        /// <param name="nameValueCollection">The collection that will be wrapped by this configuration source.</param>
        [PublicApi]
        public NameValueConfigurationSource(NameValueCollection nameValueCollection)
            : this(nameValueCollection, ConfigurationOrigins.Code)
        {
            TelemetryFactory.Metrics.Record(PublicApiUsage.NameValueConfigurationSource_Ctor);
        }

        internal NameValueConfigurationSource(NameValueCollection nameValueCollection, ConfigurationOrigins origin)
        {
            _nameValueCollection = nameValueCollection;
            Origin = origin;
        }

        internal override ConfigurationOrigins Origin { get; }

        /// <inheritdoc />
        [PublicApi]
        public override string? GetString(string key)
        {
            return _nameValueCollection[key];
        }
    }
}
