//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="NullConfigurationSource.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

#nullable enable

using System.Collections.Generic;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Configuration;

internal class NullConfigurationSource : IConfigurationSource
{
    public static readonly NullConfigurationSource Instance = new();

    public string? GetString(string key) => null;

    public int? GetInt32(string key) => null;

    public double? GetDouble(string key) => null;

    public bool? GetBool(string key) => null;

    public IDictionary<string, string>? GetDictionary(string key) => null;

    public IDictionary<string, string>? GetDictionary(string key, bool allowOptionalMappings) => null;
}
