//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="IAmazonWebServiceResponse.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System.Net;

namespace Datadog.Trace.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SDK
{
    /// <summary>
    /// AmazonWebServiceResponse interface for ducktyping
    /// </summary>
    internal interface IAmazonWebServiceResponse
    {
        /// <summary>
        /// Gets the length of the content
        /// </summary>
        long ContentLength { get; }

        /// <summary>
        /// Gets the response metadata
        /// </summary>
        IResponseMetadata ResponseMetadata { get; }

        /// <summary>
        /// Gets the http status code of the AWS request
        /// </summary>
        HttpStatusCode HttpStatusCode { get; }
    }
}
