//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="IConfigurationSource.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System.Collections.Generic;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Configuration
{
    /// <summary>
    /// A source of configuration settings, identifiable by a string key.
    /// </summary>
    internal interface IConfigurationSource
    {
        /// <summary>
        /// Gets the <see cref="string"/> value of
        /// the setting with the specified key.
        /// </summary>
        /// <param name="key">The key that identifies the setting.</param>
        /// <returns>The value of the setting, or <c>null</c> if not found.</returns>
        string GetString(string key);

        /// <summary>
        /// Gets the <see cref="int"/> value of
        /// the setting with the specified key.
        /// </summary>
        /// <param name="key">The key that identifies the setting.</param>
        /// <returns>The value of the setting, or <c>null</c> if not found.</returns>
        int? GetInt32(string key);

        /// <summary>
        /// Gets the <see cref="double"/> value of
        /// the setting with the specified key.
        /// </summary>
        /// <param name="key">The key that identifies the setting.</param>
        /// <returns>The value of the setting, or <c>null</c> if not found.</returns>
        double? GetDouble(string key);

        /// <summary>
        /// Gets the <see cref="bool"/> value of
        /// the setting with the specified key.
        /// </summary>
        /// <param name="key">The key that identifies the setting.</param>
        /// <returns>The value of the setting, or <c>null</c> if not found.</returns>
        bool? GetBool(string key);

        /// <summary>
        /// Gets the <see cref="IDictionary{TKey, TValue}"/> value of
        /// the setting with the specified key.
        /// </summary>
        /// <param name="key">The key that identifies the setting.</param>
        /// <returns>The value of the setting, or <c>null</c> if not found.</returns>
        IDictionary<string, string> GetDictionary(string key);

        /// <summary>
        /// Gets the <see cref="IDictionary{TKey, TValue}"/> value of
        /// the setting with the specified key.
        /// </summary>
        /// <param name="key">The key that identifies the setting.</param>
        /// <param name="allowOptionalMappings">Determines whether to create dictionary entries when the input has no value mapping</param>
        /// <returns>The value of the setting, or <c>null</c> if not found.</returns>
        IDictionary<string, string> GetDictionary(string key, bool allowOptionalMappings);
    }
}
