//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="ImmutableIntegrationSettingsCollection.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

#nullable enable

using System.Collections.Generic;
using DatadogTestLogger.Vendors.Datadog.Trace.Logging;
using DatadogTestLogger.Vendors.Datadog.Trace.SourceGenerators;
using DatadogTestLogger.Vendors.Datadog.Trace.Telemetry;
using DatadogTestLogger.Vendors.Datadog.Trace.Telemetry.Metrics;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Configuration
{
    /// <summary>
    /// A collection of <see cref="ImmutableIntegrationSettings"/> instances, referenced by name.
    /// </summary>
    internal class ImmutableIntegrationSettingsCollection
    {
        private static readonly IDatadogLogger Log = DatadogLogging.GetLoggerFor<ImmutableIntegrationSettingsCollection>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ImmutableIntegrationSettingsCollection"/> class.
        /// </summary>
        /// <param name="settings">The <see cref="IntegrationSettingsCollection"/> to populate the immutable settings.</param>
        /// <param name="disabledIntegrationNames">Additional integrations that should be disabled</param>
        internal ImmutableIntegrationSettingsCollection(
            IntegrationSettingsCollection settings,
            HashSet<string> disabledIntegrationNames)
        {
            Settings = GetIntegrationSettingsById(settings, disabledIntegrationNames);
        }

        internal ImmutableIntegrationSettings[] Settings { get; }

        /// <summary>
        /// Gets the <see cref="ImmutableIntegrationSettings"/> for the specified integration.
        /// </summary>
        /// <param name="integrationName">The name of the integration.</param>
        /// <returns>The integration-specific settings for the specified integration.</returns>
        [PublicApi]
        public ImmutableIntegrationSettings this[string integrationName]
        {
            get
            {
                TelemetryFactory.Metrics.Record(PublicApiUsage.ImmutableIntegrationSettingsCollection_Indexer_Name);
                if (IntegrationRegistry.TryGetIntegrationId(integrationName, out var integrationId))
                {
                    return Settings[(int)integrationId];
                }

                Log.Warning(
                    "Accessed integration settings for unknown integration {IntegrationName}. Returning default settings",
                    integrationName);

                return new ImmutableIntegrationSettings(integrationName);
            }
        }

        internal ImmutableIntegrationSettings this[IntegrationId integration]
            => Settings[(int)integration];

        private static ImmutableIntegrationSettings[] GetIntegrationSettingsById(
            IntegrationSettingsCollection settings,
            HashSet<string> disabledIntegrationNames)
        {
            var allExistingSettings = settings.Settings;
            var integrations = new ImmutableIntegrationSettings[allExistingSettings.Length];

            for (int i = 0; i < integrations.Length; i++)
            {
                var existingSettings = allExistingSettings[i];
                var explicitlyDisabled = disabledIntegrationNames.Contains(existingSettings.IntegrationNameInternal);

                integrations[i] = new ImmutableIntegrationSettings(existingSettings, explicitlyDisabled);
            }

            return integrations;
        }
    }
}
