//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="IEventMessagePackFormatter.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;
using DatadogTestLogger.Vendors.Datadog.Trace.Ci.Coverage.Models;
using DatadogTestLogger.Vendors.Datadog.Trace.Ci.EventModel;
using DatadogTestLogger.Vendors.Datadog.Trace.Vendors.MessagePack;
using DatadogTestLogger.Vendors.Datadog.Trace.Vendors.MessagePack.Formatters;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Ci.Agent.MessagePack
{
    internal class IEventMessagePackFormatter : IMessagePackFormatter<IEvent>
    {
        public IEvent Deserialize(byte[] bytes, int offset, IFormatterResolver formatterResolver, out int readSize)
        {
            throw new NotImplementedException();
        }

        public int Serialize(ref byte[] bytes, int offset, IEvent value, IFormatterResolver formatterResolver)
        {
            var formatter = CIFormatterResolver.Instance;

            if (value is CIVisibilityEvent<Span> ciVisibilityEvent)
            {
                if (formatter == formatterResolver)
                {
                    return formatter.GetCiVisibilityEventFormatter().Serialize(ref bytes, offset, ciVisibilityEvent, formatterResolver);
                }

                return formatterResolver.GetFormatter<CIVisibilityEvent<Span>>().Serialize(ref bytes, offset, ciVisibilityEvent, formatterResolver);
            }

            if (value is CoveragePayload coverageEvent)
            {
                if (formatter == formatterResolver)
                {
                    return formatter.GetCoveragePayloadFormatter().Serialize(ref bytes, offset, coverageEvent, formatterResolver);
                }

                return formatterResolver.GetFormatter<CoveragePayload>().Serialize(ref bytes, offset, coverageEvent, formatterResolver);
            }

            return 0;
        }
    }
}
