//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="ProduceDeliveryCallbacks.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>
#nullable enable

using System;
using DatadogTestLogger.Vendors.Datadog.Trace.Util.Delegates;

namespace DatadogTestLogger.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.Kafka;

internal struct ProduceDeliveryCallbacks : IBegin1Callbacks, IVoidReturnCallback
{
    public void OnException(object? sender, Exception ex)
    {
    }

    public void OnDelegateEnd(object? sender, Exception? exception, object? state)
    {
    }

    public object? OnDelegateBegin<TDeliveryReport>(object? sender, ref TDeliveryReport deliveryReport)
    {
        // no need to add logic here, we just need a dummy handler
        return null;
    }
}
