//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="ConfigurationResult.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

#nullable enable

namespace DatadogTestLogger.Vendors.Datadog.Trace.Configuration.ConfigurationSources.Telemetry;

internal readonly record struct ConfigurationResult<T>
{
    private ConfigurationResult(T result, bool isValid)
    {
        Result = result;
        IsValid = isValid;
    }

    /// <summary>
    /// Gets the extracted configuration value.
    /// </summary>
    public T Result { get; }

    /// <summary>
    /// Gets a value indicating whether <see cref="Result"/> result passed validation.
    /// </summary>
    public bool IsValid { get; }

    public static ConfigurationResult<T> Valid(T result) => new(result, isValid: true);

    public static ConfigurationResult<T> Invalid(T result) => new(result, isValid: false);
}
