//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="Clock.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Util
{
    internal class Clock
    {
        /// <summary>
        /// Flag used to avoid checking the threadstatic field when running outside of tests
        /// </summary>
        private static bool _overrideClock;

        [ThreadStatic]
        private static IClock _customClock;

        public static DateTime UtcNow
        {
            get
            {
                if (!_overrideClock)
                {
                    return DateTime.UtcNow;
                }

                return _customClock?.UtcNow ?? DateTime.UtcNow;
            }
        }

        internal static void Reset()
        {
            _overrideClock = false;
        }

        /// <summary>
        /// Overrides the clock used by the current thread.
        /// This method should be called only from unit tests.
        /// </summary>
        /// <param name="customClock">Fake clock</param>
        /// <returns>Lease to dispose to restore the original state</returns>
        internal static IDisposable SetForCurrentThread(IClock customClock)
        {
            _overrideClock = true;
            _customClock = customClock;
            return new Lease();
        }

        private class Lease : IDisposable
        {
            public void Dispose()
            {
                _customClock = null;
            }
        }
    }
}
