//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="SpanIdGenerator.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;

namespace Datadog.Trace.Vendors.Datadog.Trace.Util
{
    internal class SpanIdGenerator
    {
        public static ulong CreateNew()
        {
            ulong value;
            do
            {
                long high = ThreadSafeRandom.Next(int.MinValue, int.MaxValue);
                long low = ThreadSafeRandom.Next(int.MinValue, int.MaxValue);

                // Concatenate both values, and truncate the 32 top bits from low
                value = (ulong)(high << 32 | (low & 0xFFFFFFFF)) & 0x7FFFFFFFFFFFFFFF;
            }
            while (value == 0);
            return value;
        }
    }
}
