using System.Collections;
using System.Text;

namespace DatadogTestLogger.Test;

public class DatadogTestResultSerializerTests
{
    public static IEnumerable<object[]> Data()
    {
        yield return new object[]
        {
            new Dictionary<string, string>(),
            Array.Empty<string>()
        };

        yield return new object[]
        {
            new Dictionary<string, string>
            {
                ["AGENT_BUILDDIRECTORY"] = @"D:\a\1",
                ["AGENT_CLOUDID"] = @"",
                ["AGENT_DISABLELOGPLUGIN_TESTFILEPUBLISHERPLUGIN"] = @"true",
                ["AGENT_DISABLELOGPLUGIN_TESTRESULTLOGPLUGIN"] = @"true",
                ["AGENT_HOMEDIRECTORY"] = @"C:\agent",
                ["AGENT_ID"] = @"401232",
                ["AGENT_ISSELFHOSTED"] = @"1",
                ["AGENT_JOBNAME"] = @"managed",
                ["AGENT_JOBSTATUS"] = @"Succeeded",
                ["AGENT_LOGTOBLOBSTORAGESERVICE"] = @"true",
                ["AGENT_MACHINENAME"] = @"apmdo4ffa000XOA",
                ["AGENT_NAME"] = @"apmdo4ffa000XOA",
                ["AGENT_OS"] = @"Windows_NT",
                ["AGENT_OSARCHITECTURE"] = @"X64",
                ["AGENT_READONLYVARIABLES"] = @"true",
                ["AGENT_RETAINDEFAULTENCODING"] = @"false",
                ["AGENT_ROOTDIRECTORY"] = @"D:\a",
                ["AGENT_RUNMODE"] = @"once",
                ["AGENT_SERVEROMDIRECTORY"] = @"C:\agent\externals\vstsom",
                ["AGENT_TASKRESTRICTIONSENFORCEMENTMODE"] = @"Enabled",
                ["AGENT_TEMPDIRECTORY"] = @"D:\a\_temp",
                ["AGENT_TOOLSDIRECTORY"] = @"D:\a\_tool",
                ["AGENT_USEWORKSPACEID"] = @"true",
                ["AGENT_VERSION"] = @"3.218.0",
                ["AGENT_WORKFOLDER"] = @"D:\a",
                ["agent.jobstatus"] = @"Succeeded",
                ["ALLUSERSPROFILE"] = @"C:\ProgramData",
                ["API_KEY_CHECKER_ENABLED"] = @"false",
                ["APPDATA"] = @"C:\Users\AzDevOps\AppData\Roaming",
                ["ARTIFACTS"] = @"D:\a\1\s/tracer/src/bin/artifacts",
                ["AZURE_HTTP_USER_AGENT"] = @"VSTS_124c910c-3307-4c7f-b5dc-36cb208d4211_build_54_0",
                ["AZURE_PROJECT_NAME"] = @"dd-trace-dotnet",
                ["AZURE_STORAGE_ACCOUNT_NAME"] = @"apmdotnetci",
                ["AZURE_STORAGE_CONTAINER_NAME"] = @"apm-dotnet-ci-artifacts-master",
                ["AZURE_SUBSCRIPTION_NAME"] = @"datadog-agent-build-and-demo",
                ["BUILD_ARTIFACTSTAGINGDIRECTORY"] = @"D:\a\1\a",
                ["BUILD_BINARIESDIRECTORY"] = @"D:\a\1\b",
                ["BUILD_BUILDID"] = @"133608",
                ["BUILD_BUILDNUMBER"] = @"20230331.14",
                ["BUILD_BUILDURI"] = @"vstfs:///Build/Build/133608",
                ["BUILD_CONTAINERID"] = @"19696566",
                ["BUILD_DEFINITIONFOLDERPATH"] = @"\",
                ["BUILD_DEFINITIONNAME"] = @"consolidated-pipeline",
                ["BUILD_DEFINITIONVERSION"] = @"55",
                ["BUILD_QUEUEDBY"] = @"Microsoft.VisualStudio.Services.TFS",
                ["BUILD_QUEUEDBYID"] = @"00000002-0000-8888-8000-000000000000",
                ["BUILD_REASON"] = @"IndividualCI",
                ["BUILD_REPOSITORY_CLEAN"] = @"True",
                ["BUILD_REPOSITORY_GIT_SUBMODULECHECKOUT"] = @"False",
                ["BUILD_REPOSITORY_ID"] = @"DataDog/dd-trace-dotnet",
                ["BUILD_REPOSITORY_LOCALPATH"] = @"D:\a\1\s",
                ["BUILD_REPOSITORY_NAME"] = @"DataDog/dd-trace-dotnet",
                ["BUILD_REPOSITORY_PROVIDER"] = @"GitHub",
                ["BUILD_REPOSITORY_URI"] = @"https://github.com/DataDog/dd-trace-dotnet",
                ["BUILD_REQUESTEDFOR"] = @"Microsoft.VisualStudio.Services.TFS",
                ["BUILD_REQUESTEDFORID"] = @"00000002-0000-8888-8000-000000000000",
                ["BUILD_SOURCEBRANCH"] = @"refs/heads/master",
                ["BUILD_SOURCEBRANCHNAME"] = @"master",
                ["BUILD_SOURCESDIRECTORY"] = @"D:\a\1\s",
                ["BUILD_SOURCEVERSION"] = @"647b93378e56c68cbbdd0f5e2765f49f26a96c4d",
                ["BUILD_SOURCEVERSIONAUTHOR"] = @"github-actions[bot]",
                ["BUILD_SOURCEVERSIONMESSAGE"] = @"[Test Package Versions Bump] (#3978)",
                ["BUILD_STAGINGDIRECTORY"] = @"D:\a\1\a",
                ["BUILDCONFIGURATION"] = @"Release",
                ["ChocolateyInstall"] = @"C:\ProgramData\chocolatey",
                ["COMMON_TESTRESULTSDIRECTORY"] = @"D:\a\1\TestResults",
                ["CommonProgramFiles"] = @"C:\Program Files\Common Files",
                ["CommonProgramFiles(x86)"] = @"C:\Program Files (x86)\Common Files",
                ["CommonProgramW6432"] = @"C:\Program Files\Common Files",
                ["COMPlus_DbgEnableMiniDump"] = @"1",
                ["COMPlus_DbgMiniDumpType"] = @"4",
                ["COMPUTERNAME"] = @"apmdo4ffa000XOA",
                ["ComSpec"] = @"C:\Windows\system32\cmd.exe",
                ["DD_API_KEY"] = @"1234567890",
                ["DD_APPSEC_ENABLED"] = @"false",
                ["DD_CIVISIBILITY_AGENTLESS_ENABLED"] = @"true",
                ["DD_CIVISIBILITY_ENABLED"] = @"true",
                ["DD_CIVISIBILITY_LOGS_ENABLED"] = @"true",
                ["DD_CLR_ENABLE_NGEN"] = @"",
                ["DD_DOTNET_TRACER_MSBUILD"] = @"",
                ["DD_ENV"] = @"CI",
                ["DD_INSTRUMENTATION_TELEMETRY_AGENT_PROXY_ENABLED"] = @"false",
                ["DD_INSTRUMENTATION_TELEMETRY_AGENTLESS_ENABLED"] = @"false",
                ["DD_INSTRUMENTATION_TELEMETRY_ENABLED"] = @"false",
                ["DD_LOGGER_API_KEY_CHECKER_ENABLED"] = @"false",
                ["DD_LOGGER_BUILD_BUILDID"] = @"133608",
                ["DD_LOGGER_BUILD_DEFINITIONNAME"] = @"consolidated-pipeline",
                ["DD_LOGGER_BUILD_REPOSITORY_URI"] = @"https://github.com/DataDog/dd-trace-dotnet",
                ["DD_LOGGER_BUILD_REQUESTEDFOREMAIL"] = @"",
                ["DD_LOGGER_BUILD_REQUESTEDFORID"] = @"00000002-0000-8888-8000-000000000000",
                ["DD_LOGGER_BUILD_SOURCEBRANCH"] = @"refs/heads/master",
                ["DD_LOGGER_BUILD_SOURCEBRANCHNAME"] = @"master",
                ["DD_LOGGER_BUILD_SOURCESDIRECTORY"] = @"D:\a\1\s",
                ["DD_LOGGER_BUILD_SOURCEVERSION"] = @"647b93378e56c68cbbdd0f5e2765f49f26a96c4d",
                ["DD_LOGGER_BUILD_SOURCEVERSIONMESSAGE"] = @"[Test Package Versions Bump] (#3978)",
                ["DD_LOGGER_DD_API_KEY"] = @"1234567890",
                ["DD_LOGGER_DD_APPSEC_ENABLED"] = @"false",
                ["DD_LOGGER_DD_CIVISIBILITY_AGENTLESS_ENABLED"] = @"true",
                ["DD_LOGGER_DD_CIVISIBILITY_ENABLED"] = @"true",
                ["DD_LOGGER_DD_CIVISIBILITY_LOGS_ENABLED"] = @"true",
                ["DD_LOGGER_DD_ENV"] = @"CI",
                ["DD_LOGGER_DD_INSTRUMENTATION_TELEMETRY_AGENT_PROXY_ENABLED"] = @"false",
                ["DD_LOGGER_DD_INSTRUMENTATION_TELEMETRY_AGENTLESS_ENABLED"] = @"false",
                ["DD_LOGGER_DD_INSTRUMENTATION_TELEMETRY_ENABLED"] = @"false",
                ["DD_LOGGER_DD_PROFILING_ENABLED"] = @"false",
                ["DD_LOGGER_DD_SERVICE"] = @"dd-trace-dotnet",
                ["DD_LOGGER_DD_TAGS"] = @"test.configuration.job:managed",
                ["DD_LOGGER_ENABLED"] = @"true",
                ["DD_LOGGER_SYSTEM_JOBDISPLAYNAME"] = @"managed",
                ["DD_LOGGER_SYSTEM_JOBID"] = @"61ef1a4a-6239-5ffb-3d52-8f25bbbf347b",
                ["DD_LOGGER_SYSTEM_PULLREQUEST_SOURCEBRANCH"] = @"",
                ["DD_LOGGER_SYSTEM_PULLREQUEST_SOURCECOMMITID"] = @"",
                ["DD_LOGGER_SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI"] = @"",
                ["DD_LOGGER_SYSTEM_STAGEDISPLAYNAME"] = @"unit_tests_windows",
                ["DD_LOGGER_SYSTEM_TEAMFOUNDATIONSERVERURI"] = @"https://dev.azure.com/datadoghq/",
                ["DD_LOGGER_SYSTEM_TEAMPROJECTID"] = @"a51c4863-3eb4-4c5d-878a-58b41a049e4e",
                ["DD_LOGGER_TF_BUILD"] = @"True",
                ["DD_PROFILING_ENABLED"] = @"false",
                ["DD_SERVICE"] = @"dd-trace-dotnet",
                ["DD_SERVICE_NAME"] = @"dd-tracer-dotnet",
                ["DD_TAGS"] = @"test.configuration.job:managed",
                ["DD_TRACE_LOG_DIRECTORY"] = @"D:\a\1\s\tracer\build_data\logs",
                ["DEFAULTTIMEOUT"] = @"60",
                ["DIFFENGINE_DISABLED"] = @"true",
                ["DOTNET_CLI_TELEMETRY_SESSIONID"] = @"4546b763-ac62-409f-ad11-7e170f149ea9",
                ["DOTNET_CLI_UI_LANGUAGE"] = @"en",
                ["DOTNET_EXE"] = @"D:\a\_tool/dotnet\dotnet.exe",
                ["DOTNET_HOST_PATH"] = @"D:\a\_tool\dotnet\dotnet.exe",
                ["DOTNET_MULTILEVEL_LOOKUP"] = @"0",
                ["DOTNET_ROOT"] = @"D:\a\_tool/dotnet",
                ["DOTNET_ROOT_X64"] = @"D:\a\_tool\dotnet",
                ["DOTNETCORESDKLATESTVERSION"] = @"7.0.101",
                ["DOTNETTOOLTAG"] = @"build-dotnet-tool",
                ["DOWNLOADPIPELINEARTIFACT_BUILDNUMBER"] = @"133608",
                ["DriverData"] = @"C:\Windows\System32\Drivers\DriverData",
                ["ENABLE_CRASH_DUMPS"] = @"true",
                ["ENABLED"] = @"true",
                ["FORCE_EXPLORATION_TESTS_WITH_ISDEBUGGERCHANGED"] = @"false",
                ["FORCE_EXPLORATION_TESTS_WITH_ISPROFILERCHANGED"] = @"false",
                ["FORCE_EXPLORATION_TESTS_WITH_ISTRACERCHANGED"] = @"false",
                ["GCM_INTERACTIVE"] = @"Never",
                ["GIT_PROFILER_REF"] = @"master",
                ["GIT_TERMINAL_PROMPT"] = @"0",
                ["GITHUB_REPOSITORY_NAME"] = @"dd-trace-dotnet",
                ["INCLUDEALLTESTFRAMEWORKS"] = @"True",
                ["IncludePrereleaseVersions"] = @"false",
                ["ISBENCHMARKSONLYBUILD"] = @"False",
                ["ISMAINBRANCH"] = @"True",
                ["ISMAINORRELEASEBRANCH"] = @"True",
                ["ISMAINREPOSITORY"] = @"True",
                ["ISPULLREQUEST"] = @"False",
                ["LOCALAPPDATA"] = @"C:\Users\AzDevOps\AppData\Local",
                ["MONITORINGHOME"] = @"D:\a\1\s/shared/bin/monitoring-home",
                ["MSBUILDENSURESTDOUTFORTASKPROCESSES"] = @"1",
                ["MSBuildExtensionsPath"] = @"D:\a\_tool\dotnet\sdk\7.0.101\",
                ["MSBuildLoadMicrosoftTargetsReadOnly"] = @"true",
                ["MSBuildSDKsPath"] = @"D:\a\_tool\dotnet\sdk\7.0.101\Sdks",
                ["MSBUILDUSESERVER"] = @"0",
                ["MSDEPLOY_HTTP_USER_AGENT"] = @"VSTS_124c910c-3307-4c7f-b5dc-36cb208d4211_build_54_0",
                ["NUGET_ENABLE_EXPERIMENTAL_HTTP_RETRY"] = @"true",
                ["NUGETPACKAGEDIRECTORY"] = @"D:\a\1\s/packages",
                ["NUMBER_OF_PROCESSORS"] = @"2",
                ["ORIGINALCOMMITID"] = @"647b93378e56c68cbbdd0f5e2765f49f26a96c4d",
                ["OS"] = @"Windows_NT",
                ["Path"] =
                    @"C:\Users\AzDevOps\.dotnet\tools;D:\a\_tool/dotnet;C:\agent\externals\git\cmd;C:\agent\externals\git\mingw64\bin;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\vcpkg;C:\Program Files\Git\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\AzDevOps\AppData\Local\Microsoft\WindowsApps",
                ["PATHEXT"] = @".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
                ["PERFORM_COMPREHENSIVE_TESTING"] = @"false",
                ["PIPELINE_WORKSPACE"] = @"D:\a\1",
                ["PreferredUILang"] = @"en",
                ["PROCESSOR_ARCHITECTURE"] = @"AMD64",
                ["PROCESSOR_IDENTIFIER"] = @"AMD64 Family 25 Model 1 Stepping 1, AuthenticAMD",
                ["PROCESSOR_LEVEL"] = @"25",
                ["PROCESSOR_REVISION"] = @"0101",
                ["ProgramData"] = @"C:\ProgramData",
                ["ProgramFiles"] = @"C:\Program Files",
                ["ProgramFiles(x86)"] = @"C:\Program Files (x86)",
                ["ProgramW6432"] = @"C:\Program Files",
                ["PROMPT"] = @"$P$G",
                ["PSExecutionPolicyPreference"] = @"Bypass",
                ["PSModulePath"] =
                    @"C:\Users\AzDevOps\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules",
                ["PUBLIC"] = @"C:\Users\Public",
                ["PUSH_ARTIFACTS_TO_AZURE_STORAGE"] = @"",
                ["PUSH_ARTIFACTS_TO_S3"] = @"",
                ["RELATIVEARTIFACTS"] = @"/tracer/src/bin/artifacts",
                ["RELATIVENUGETPACKAGEDIRECTORY"] = @"packages",
                ["RELATIVERUNNERSTANDALONE"] = @"tracer/src/bin/runnerStandalone",
                ["RELATIVERUNNERTOOL"] = @"tracer/src/bin/runnerTool",
                ["RESOURCES_TRIGGERINGALIAS"] = @"",
                ["RESOURCES_TRIGGERINGCATEGORY"] = @"",
                ["RUN_ALL_INSTALLER_TESTS"] = @"false",
                ["RUN_ALL_TEST_FRAMEWORKS"] = @"false",
                ["RUN_AZURE_FUNCTIONS_TESTS"] = @"False",
                ["RUN_COSMOS_INTEGRATION_TESTS"] = @"false",
                ["RUN_EXTENDED_THROUGHPUT_TESTS"] = @"false",
                ["SYMBOLS"] = @"D:\a\1\s/tracer/bin/symbols",
                ["SYSTEM"] = @"build",
                ["SYSTEM_ARTIFACTSDIRECTORY"] = @"D:\a\1\a",
                ["SYSTEM_COLLECTIONID"] = @"124c910c-3307-4c7f-b5dc-36cb208d4211",
                ["SYSTEM_COLLECTIONURI"] = @"https://dev.azure.com/datadoghq/",
                ["SYSTEM_CULTURE"] = @"en-US",
                ["SYSTEM_DEFAULTWORKINGDIRECTORY"] = @"D:\a\1\s",
                ["SYSTEM_DEFINITIONID"] = @"54",
                ["SYSTEM_DEFINITIONNAME"] = @"consolidated-pipeline",
                ["SYSTEM_ENABLEACCESSTOKEN"] = @"SecretVariable",
                ["SYSTEM_HOSTTYPE"] = @"build",
                ["SYSTEM_ISAZUREVM"] = @"1",
                ["SYSTEM_ISDOCKERCONTAINER"] = @"0",
                ["SYSTEM_ISSCHEDULED"] = @"False",
                ["SYSTEM_JOBATTEMPT"] = @"1",
                ["SYSTEM_JOBDISPLAYNAME"] = @"managed",
                ["SYSTEM_JOBID"] = @"61ef1a4a-6239-5ffb-3d52-8f25bbbf347b",
                ["SYSTEM_JOBIDENTIFIER"] = @"unit_tests_windows.managed.__default",
                ["SYSTEM_JOBNAME"] = @"__default",
                ["SYSTEM_JOBPARALLELISMTAG"] = @"Public",
                ["SYSTEM_JOBPOSITIONINPHASE"] = @"1",
                ["SYSTEM_JOBTIMEOUT"] = @"60",
                ["SYSTEM_PHASEATTEMPT"] = @"1",
                ["SYSTEM_PHASEDISPLAYNAME"] = @"managed",
                ["SYSTEM_PHASEID"] = @"a4b41ab5-c27a-54bc-ce62-69ec3e89a7e3",
                ["SYSTEM_PHASENAME"] = @"managed",
                ["SYSTEM_PIPELINESTARTTIME"] = @"2023-03-31 08:40:03+00:00",
                ["SYSTEM_PLANID"] = @"8d77d8eb-b9ab-4ad8-a748-ee0dc6e715c5",
                ["SYSTEM_POSTLINESSPEED"] = @"10000",
                ["SYSTEM_PULLREQUEST_ISFORK"] = @"False",
                ["SYSTEM_SERVERTYPE"] = @"Hosted",
                ["SYSTEM_STAGEATTEMPT"] = @"1",
                ["SYSTEM_STAGEDISPLAYNAME"] = @"unit_tests_windows",
                ["SYSTEM_STAGEID"] = @"bf6a0625-31e3-558a-2844-9ea1d941aca7",
                ["SYSTEM_STAGENAME"] = @"unit_tests_windows",
                ["SYSTEM_TASKDEFINITIONSURI"] = @"https://dev.azure.com/datadoghq/",
                ["SYSTEM_TASKDISPLAYNAME"] = @"Build and Test",
                ["SYSTEM_TASKINSTANCEID"] = @"c641a42e-b4ea-56b0-462d-84f194465978",
                ["SYSTEM_TASKINSTANCENAME"] = @"CmdLine",
                ["SYSTEM_TEAMFOUNDATIONCOLLECTIONURI"] = @"https://dev.azure.com/datadoghq/",
                ["SYSTEM_TEAMFOUNDATIONSERVERURI"] = @"https://dev.azure.com/datadoghq/",
                ["SYSTEM_TEAMPROJECT"] = @"dd-trace-dotnet",
                ["SYSTEM_TEAMPROJECTID"] = @"a51c4863-3eb4-4c5d-878a-58b41a049e4e",
                ["SYSTEM_TIMELINEID"] = @"8d77d8eb-b9ab-4ad8-a748-ee0dc6e715c5",
                ["SYSTEM_TOTALJOBSINPHASE"] = @"1",
                ["SYSTEM_WORKFOLDER"] = @"D:\a",
                ["SystemDrive"] = @"C:",
                ["SystemRoot"] = @"C:\Windows",
                ["TARGETBRANCH"] = @"master",
                ["TARGETSHAID"] = @"647b93378e56c68cbbdd0f5e2765f49f26a96c4d",
                ["TASK_DISPLAYNAME"] = @"Build and Test",
                ["TASK_SKIPTRANSLATORFORCHECKOUT"] = @"False",
                ["TEMP"] = @"C:\Users\AzDevOps\AppData\Local\Temp",
                ["TF_BUILD"] = @"True",
                ["TMP"] = @"C:\Users\AzDevOps\AppData\Local\Temp",
                ["USE_NATIVE_LOADER"] = @"false",
                ["USERDOMAIN"] = @"apmdo4ffa000XOA",
                ["USERNAME"] = @"AzDevOps",
                ["USERPROFILE"] = @"C:\Users\AzDevOps",
                ["VCPKG_INSTALLATION_ROOT"] = @"C:\vcpkg",
                ["VERBOSE_ARG"] = @"'SilentlyContinue'",
                ["VERIFY_DISABLECLIPBOARD"] = @"true",
                ["VSLANG"] = @"9",
                ["VSTS_PROCESS_LOOKUP_ID"] = @"vsts_dbe84b1b-2050-41f6-9425-c998593de2cd",
                ["VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT"] = @"true",
                ["VSTSAGENT_DOCKER_ACTION_RETRIES"] = @"true",
                ["windir"] = @"C:\Windows",
                ["WIX"] = @"C:\Program Files (x86)\WiX Toolset v3.11\",
            },
            new[]
            {
                @"BUILD_BUILDID=133608",
                @"BUILD_DEFINITIONNAME=consolidated-pipeline",
                @"BUILD_REPOSITORY_URI=https://github.com/DataDog/dd-trace-dotnet",
                @"BUILD_REQUESTEDFORID=***********************************",
                @"BUILD_SOURCEBRANCH=refs/heads/master",
                @"BUILD_SOURCEBRANCHNAME=master",
                @"BUILD_SOURCESDIRECTORY=D:\a\1\s",
                @"BUILD_SOURCEVERSION=647b93378e56c68cbbdd0f5e2765f49f26a96c4d",
                @"BUILD_SOURCEVERSIONMESSAGE=[Test Package Versions Bump] (#3978)",
                @"DD_API_KEY=***********************************",
                @"DD_APPSEC_ENABLED=false",
                @"DD_CIVISIBILITY_AGENTLESS_ENABLED=true",
                @"DD_CIVISIBILITY_ENABLED=true",
                @"DD_CIVISIBILITY_LOGS_ENABLED=true",
                @"DD_CLR_ENABLE_NGEN=",
                @"DD_DOTNET_TRACER_MSBUILD=",
                @"DD_ENV=CI",
                @"DD_INSTRUMENTATION_TELEMETRY_AGENTLESS_ENABLED=false",
                @"DD_INSTRUMENTATION_TELEMETRY_AGENT_PROXY_ENABLED=false",
                @"DD_INSTRUMENTATION_TELEMETRY_ENABLED=false",
                @"DD_LOGGER_API_KEY_CHECKER_ENABLED=***********************************",
                @"DD_LOGGER_BUILD_BUILDID=133608",
                @"DD_LOGGER_BUILD_DEFINITIONNAME=consolidated-pipeline",
                @"DD_LOGGER_BUILD_REPOSITORY_URI=https://github.com/DataDog/dd-trace-dotnet",
                @"DD_LOGGER_BUILD_REQUESTEDFOREMAIL=",
                @"DD_LOGGER_BUILD_REQUESTEDFORID=***********************************",
                @"DD_LOGGER_BUILD_SOURCEBRANCH=refs/heads/master",
                @"DD_LOGGER_BUILD_SOURCEBRANCHNAME=master",
                @"DD_LOGGER_BUILD_SOURCESDIRECTORY=D:\a\1\s",
                @"DD_LOGGER_BUILD_SOURCEVERSION=647b93378e56c68cbbdd0f5e2765f49f26a96c4d",
                @"DD_LOGGER_BUILD_SOURCEVERSIONMESSAGE=[Test Package Versions Bump] (#3978)",
                @"DD_LOGGER_DD_API_KEY=***********************************",
                @"DD_LOGGER_DD_APPSEC_ENABLED=false",
                @"DD_LOGGER_DD_CIVISIBILITY_AGENTLESS_ENABLED=true",
                @"DD_LOGGER_DD_CIVISIBILITY_ENABLED=true",
                @"DD_LOGGER_DD_CIVISIBILITY_LOGS_ENABLED=true",
                @"DD_LOGGER_DD_ENV=CI",
                @"DD_LOGGER_DD_INSTRUMENTATION_TELEMETRY_AGENTLESS_ENABLED=false",
                @"DD_LOGGER_DD_INSTRUMENTATION_TELEMETRY_AGENT_PROXY_ENABLED=false",
                @"DD_LOGGER_DD_INSTRUMENTATION_TELEMETRY_ENABLED=false",
                @"DD_LOGGER_DD_PROFILING_ENABLED=false",
                @"DD_LOGGER_DD_SERVICE=dd-trace-dotnet",
                @"DD_LOGGER_DD_TAGS=test.configuration.job:managed",
                @"DD_LOGGER_ENABLED=true",
                @"DD_LOGGER_SYSTEM_JOBDISPLAYNAME=managed",
                @"DD_LOGGER_SYSTEM_JOBID=***********************************",
                @"DD_LOGGER_SYSTEM_PULLREQUEST_SOURCEBRANCH=",
                @"DD_LOGGER_SYSTEM_PULLREQUEST_SOURCECOMMITID=",
                @"DD_LOGGER_SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI=",
                @"DD_LOGGER_SYSTEM_STAGEDISPLAYNAME=unit_tests_windows",
                @"DD_LOGGER_SYSTEM_TEAMFOUNDATIONSERVERURI=https://dev.azure.com/datadoghq/",
                @"DD_LOGGER_SYSTEM_TEAMPROJECTID=***********************************",
                @"DD_LOGGER_TF_BUILD=True",
                @"DD_PROFILING_ENABLED=false",
                @"DD_SERVICE=dd-trace-dotnet",
                @"DD_SERVICE_NAME=dd-tracer-dotnet",
                @"DD_TAGS=test.configuration.job:managed",
                @"DD_TRACE_LOG_DIRECTORY=D:\a\1\s\tracer\build_data\logs",
                @"SYSTEM_JOBDISPLAYNAME=managed",
                @"SYSTEM_JOBID=***********************************",
                @"SYSTEM_STAGEDISPLAYNAME=unit_tests_windows",
                @"SYSTEM_TASKINSTANCEID=***********************************",
                @"SYSTEM_TEAMFOUNDATIONSERVERURI=https://dev.azure.com/datadoghq/",
                @"SYSTEM_TEAMPROJECTID=***********************************",
                @"TF_BUILD=True",
                @"USERPROFILE=C:\Users\AzDevOps",
            }
        };
    }

    [Theory]
    [MemberData(nameof(Data))]
    public void ShowEnvironmentVariables(IDictionary environmentVariables, string[] variables)
    {
        var sb = new StringBuilder();
        new DatadogTestResultSerializer().ShowEnvironmentVariables(sb, string.Empty, environmentVariables);
        var envVars = sb.ToString()
            .Split(new[] { "\n", "\r\n" }, StringSplitOptions.RemoveEmptyEntries)
            .Select(i => i.Trim())
            .ToArray();

        Array.Sort(variables);
        Array.Sort(envVars);

        Assert.Equal(envVars.Length, variables.Length);
        for (var i = 0; i < envVars.Length; i++)
        {
            if (envVars[i] != variables[i])
            {
                Assert.Equal(variables[i], envVars[i]);
            }
        }
    }
}