//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="SamplingPriorityValues.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

namespace DatadogTestLogger.Vendors.Datadog.Trace
{
    internal static class SamplingPriorityValues
    {
        /// <summary>
        /// Trace should be dropped (not sampled).
        /// Sampling decision made explicitly by user through
        /// code or configuration (e.g. the rules sampler).
        /// </summary>
        public const int UserReject = -1;

        /// <summary>
        /// Trace should be dropped (not sampled).
        /// Sampling decision made by the built-in sampler.
        /// </summary>
        public const int AutoReject = 0;

        /// <summary>
        /// Trace should be kept (sampled).
        /// Sampling decision made by the built-in sampler.
        /// </summary>
        public const int AutoKeep = 1;

        /// <summary>
        /// Trace should be kept (sampled).
        /// Sampling decision made explicitly by user through
        /// code or configuration (e.g. the rules sampler).
        /// </summary>
        public const int UserKeep = 2;
    }
}
