//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="SpanCreationSettings.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;

namespace DatadogTestLogger.Vendors.Datadog.Trace
{
    /// <summary>
    /// Settings to use when creating a new <see cref="IScope"/> and <see cref="ISpan"/>.
    /// </summary>
    internal struct SpanCreationSettings
    {
        /// <summary>
        /// Gets or sets an explicit start time for the new span. If not set, uses the current time.
        /// </summary>
        public DateTimeOffset? StartTime { get; set; }

        /// <summary>
        /// Gets or sets the new span's parent. To prevent a new span from inheriting a parent,
        /// set to <see cref="SpanContext.None"/>. If not set, defaults to <c>null</c> and
        /// the currently active span (if any) is used as the parent.
        /// </summary>
        public ISpanContext Parent { get; set; }

        /// <summary>
        /// Gets or sets whether closing the new scope will close the contained span.
        /// If not set, defaults to <c>true</c>.
        /// </summary>
        public bool? FinishOnClose { get; set; }
    }
}
