//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="DssSymbolReaderImpl.Additions.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;
using DatadogTestLogger.Vendors.Datadog.Trace.Vendors.dnlib.DotNet.Pdb.Symbols;

#pragma warning disable SA1300
namespace DatadogTestLogger.Vendors.Datadog.Trace.Vendors.dnlib.DotNet.Pdb.Dss
{
    internal sealed partial class SymbolReaderImpl
    {
        internal SymbolMethod GetContainingMethod(string documentUrl, int line, int? column, out int? bytecodeOffset)
        {
            reader.GetDocument(documentUrl, language: default, languageVendor: default, documentType: default, out var document);
            reader.GetMethodFromDocumentPosition(document, (uint)line, (uint)(column ?? 0), out var method);
            method.GetOffset(document, (uint)line, (uint)(column ?? 0), out var offset);
            method.GetToken(out var token);

            bytecodeOffset = (int?)offset;
            return new SymbolMethodImpl(this, method);
        }
    }
}
