//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="SymmetricAlgorithmIntegrationCommon.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

#nullable enable

using System;
using Datadog.Trace.Vendors.Datadog.Trace.Configuration;
using Datadog.Trace.Vendors.Datadog.Trace.Iast;
using Datadog.Trace.Vendors.Datadog.Trace.Logging;

namespace Datadog.Trace.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.CryptographyAlgorithm;

internal class SymmetricAlgorithmIntegrationCommon
{
    internal const IntegrationId IntegrationId = Configuration.IntegrationId.SymmetricAlgorithm;
    private static readonly IDatadogLogger Log = DatadogLogging.GetLoggerFor(typeof(SymmetricAlgorithmIntegrationCommon));

    internal static Scope? CreateScope<TTarget>(TTarget instance)
    {
        var iast = Iast.Iast.Instance;

        if (!iast.Settings.Enabled)
        {
            return null;
        }

        try
        {
            return ((instance is null) ? null : IastModule.OnCipherAlgorithm(instance.GetType(), IntegrationId, iast));
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Error creating or populating SymmetricAlgorithm scope.");
            return null;
        }
    }
}
