//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="DebuggerTransportStrategy.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>
#nullable enable

using System;
using Datadog.Trace.Vendors.Datadog.Trace.Agent;
using Datadog.Trace.Vendors.Datadog.Trace.Agent.Transports;
using Datadog.Trace.Vendors.Datadog.Trace.Logging;

namespace Datadog.Trace.Vendors.Datadog.Trace.Debugger
{
    internal static class DebuggerTransportStrategy
    {
        private static readonly IDatadogLogger Log = DatadogLogging.GetLoggerFor(typeof(DebuggerTransportStrategy));

        public static IApiRequestFactory Get(Uri baseEndpoint)
        {
#if NETCOREAPP
            Log.Information("Using {FactoryType} for debugger transport.", nameof(HttpClientRequestFactory));
            return new HttpClientRequestFactory(baseEndpoint, AgentHttpHeaderNames.DefaultHeaders);
#else
            Log.Information("Using {FactoryType} for debugger transport.", nameof(ApiWebRequestFactory));
            return new ApiWebRequestFactory(baseEndpoint, AgentHttpHeaderNames.DefaultHeaders);
#endif
        }
    }
}
