//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="ContinuationGenerator.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System;
using System.Runtime.CompilerServices;

namespace DatadogTestLogger.Vendors.Datadog.Trace.ClrProfiler.CallTarget.Handlers.Continuations
{
    internal class ContinuationGenerator<TTarget, TReturn>
    {
        public virtual TReturn SetContinuation(TTarget instance, TReturn returnValue, Exception exception, in CallTargetState state)
        {
            return returnValue;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        protected static TReturn ToTReturn<TFrom>(TFrom returnValue)
        {
#if NETCOREAPP3_1_OR_GREATER
            return Unsafe.As<TFrom, TReturn>(ref returnValue);
#else
            return ContinuationsHelper.Convert<TFrom, TReturn>(returnValue);
#endif
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        protected static TTo FromTReturn<TTo>(TReturn returnValue)
        {
#if NETCOREAPP3_1_OR_GREATER
            return Unsafe.As<TReturn, TTo>(ref returnValue);
#else
            return ContinuationsHelper.Convert<TReturn, TTo>(returnValue);
#endif
        }
    }
}
