//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="HttpContextServerCallContextLogCallEndIntegration.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>
#if !NETFRAMEWORK

#nullable enable

using System.ComponentModel;
using DatadogTestLogger.Vendors.Datadog.Trace.ClrProfiler.CallTarget;
using DatadogTestLogger.Vendors.Datadog.Trace.Configuration;
using DatadogTestLogger.Vendors.Datadog.Trace.DuckTyping;
using DatadogTestLogger.Vendors.Datadog.Trace.ExtensionMethods;
using DatadogTestLogger.Vendors.Datadog.Trace.Tagging;

namespace DatadogTestLogger.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.Grpc.GrpcDotNet.GrpcAspNetCoreServer
{
    /// <summary>
    /// Grpc.Net.Client.Internal.GrpcCall calltarget instrumentation
    /// </summary>
    [InstrumentMethod(
        AssemblyName = "Grpc.AspNetCore.Server",
        TypeName = "Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext",
        MethodName = "LogCallEnd",
        ReturnTypeName = ClrNames.Void,
        MinimumVersion = "2.0.0",
        MaximumVersion = "2.*.*",
        IntegrationName = nameof(Grpc))]
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal class HttpContextServerCallContextLogCallEndIntegration
    {
        /// <summary>
        /// OnMethodBegin callback
        /// </summary>
        /// <typeparam name="TTarget">Type of the target</typeparam>
        /// <param name="instance">Instance value, aka `this` of the instrumented method.</param>
        /// <returns>Calltarget state value</returns>
        internal static CallTargetState OnMethodBegin<TTarget>(TTarget instance)
        {
            var tracer = Tracer.Instance;
            if (GrpcCoreApiVersionHelper.IsSupported
             && tracer.Settings.IsIntegrationEnabled(IntegrationId.Grpc)
             && tracer.ActiveScope?.Span is Span { Tags: GrpcServerTags } span)
            {
                var callContext = instance.DuckCast<HttpContextServerCallContextStruct>();
                var status = callContext.StatusCore;
                GrpcCommon.RecordFinalStatus(span, status.StatusCode, status.Detail, status.DebugException);

                if (callContext.RequestHeaders is { Count: > 0 } requestMetadata)
                {
                    span.SetHeaderTags(new MetadataHeadersCollection(requestMetadata), tracer.Settings.GrpcTags, defaultTagPrefix: GrpcCommon.RequestMetadataTagPrefix);
                }

                if (callContext.ResponseTrailers is { Count: > 0 } responseMetadata)
                {
                    span.SetHeaderTags(new MetadataHeadersCollection(responseMetadata), tracer.Settings.GrpcTags, defaultTagPrefix: GrpcCommon.ResponseMetadataTagPrefix);
                }
            }

            return CallTargetState.GetDefault();
        }
    }
}
#endif
