//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="ILoggingRulesListProxy.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System.ComponentModel;
using Datadog.Trace.Vendors.Datadog.Trace.DuckTyping;

namespace Datadog.Trace.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.NLog.DirectSubmission.Proxies.Pre43
{
    /// <summary>
    /// Duck type for IList&lt;LoggingRule&gt;
    /// </summary>
    internal interface ILoggingRulesListProxy
    {
        /// <summary>
        /// Adds the logging rule to the collection
        /// </summary>
        /// <param name="item">The logging rule to add to the collection</param>
        [Duck(ParameterTypeNames = new[] { "NLog.Config.LoggingRule, NLog" })]
        public void Add(object item);
    }
}
