//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="LiveProbeResolveStatus.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

namespace DatadogTestLogger.Vendors.Datadog.Trace.Debugger.Models
{
    internal enum LiveProbeResolveStatus
    {
        /// <summary>
        /// The Line Probe was successfully bound to a bytecode offset.
        /// </summary>
        Bound,

        /// <summary>
        /// The Line Probe location did not map out to any loaded module.
        /// The probe will be re-examined whenever a new module is loaded.
        /// </summary>
        Unbound,

        /// <summary>
        /// The probe could not be resolved due to an error.
        /// </summary>
        Error
    }
}
