//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace DatadogTestLogger.Vendors.Datadog.Trace.Vendors.StatsdClient
{
    internal interface IStopwatch
    {
        void Start();

        void Stop();

        int ElapsedMilliseconds();
    }
}