//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
//
// Author:
//   Jb Evain (jbevain@gmail.com)
//
// Copyright (c) 2008 - 2015 Jb Evain
// Copyright (c) 2008 - 2011 Novell, Inc.
//
// Licensed under the MIT/X11 license.
//

namespace DatadogTestLogger.Vendors.Mono.Cecil {

	enum FileAttributes : uint {
		ContainsMetaData	= 0x0000,	// This is not a resource file
		ContainsNoMetaData  = 0x0001,	// This is a resource file or other non-metadata-containing file
	}
}
