//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="WebHeadersExtensions.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

#if NETFRAMEWORK

using System;
using System.Net;
using DatadogTestLogger.Vendors.Datadog.Trace.Headers;
using DatadogTestLogger.Vendors.Datadog.Trace.Util;

namespace DatadogTestLogger.Vendors.Datadog.Trace.ExtensionMethods
{
    /// <summary>
    /// Extension methods for <see cref="WebHeaderCollection"/> objects.
    /// </summary>
    internal static class WebHeadersExtensions
    {
        /// <summary>
        /// Provides an <see cref="WebHeadersCollection"/> implementation that wraps the specified <see cref="WebHeaderCollection"/>.
        /// </summary>
        /// <param name="headers">The Web headers to wrap.</param>
        /// <returns>An object that implements <see cref="IHeadersCollection"/>.</returns>
        public static WebHeadersCollection Wrap(this WebHeaderCollection headers)
        {
            if (headers == null)
            {
                ThrowHelper.ThrowArgumentNullException(nameof(headers));
            }

            return new WebHeadersCollection(headers);
        }
    }
}

#endif
