//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="XUnitTestOutputHelperQueueTestOutputIntegration.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>
#nullable enable

using System.ComponentModel;
using DatadogTestLogger.Vendors.Datadog.Trace.Ci;
using DatadogTestLogger.Vendors.Datadog.Trace.Ci.Logging.DirectSubmission;
using DatadogTestLogger.Vendors.Datadog.Trace.ClrProfiler.CallTarget;
using DatadogTestLogger.Vendors.Datadog.Trace.Logging.DirectSubmission;

namespace DatadogTestLogger.Vendors.Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit;

/// <summary>
/// Xunit.Sdk.TestOutputHelper.QueueTestOutput calltarget instrumentation
/// </summary>
[InstrumentMethod(
    AssemblyNames = new[] { "xunit.execution.dotnet", "xunit.execution.desktop" },
    TypeName = "Xunit.Sdk.TestOutputHelper",
    MethodName = "QueueTestOutput",
    ReturnTypeName = ClrNames.Void,
    ParameterTypeNames = new[] { ClrNames.String },
    MinimumVersion = "2.2.0",
    MaximumVersion = "2.*.*",
    IntegrationName = XUnitIntegration.IntegrationName)]
[Browsable(false)]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static class XUnitTestOutputHelperQueueTestOutputIntegration
{
    /// <summary>
    /// OnMethodBegin callback
    /// </summary>
    /// <typeparam name="TTarget">Type of the target</typeparam>
    /// <param name="instance">Instance value, aka `this` of the instrumented method.</param>
    /// <param name="output">Output string</param>
    /// <returns>Calltarget state value</returns>
    internal static CallTargetState OnMethodBegin<TTarget>(TTarget instance, string output)
    {
        if (!XUnitIntegration.IsEnabled)
        {
            return CallTargetState.GetDefault();
        }

        var tracer = Tracer.Instance;
        if (tracer.TracerManager.DirectLogSubmission.Settings.MinimumLevel < DirectSubmissionLogLevel.Information)
        {
            return CallTargetState.GetDefault();
        }

        if (Test.Current?.GetInternalSpan() is { } span)
        {
            tracer.TracerManager.DirectLogSubmission.Sink.EnqueueLog(new CIVisibilityLogEvent("xunit", "info", output, span));
        }

        return CallTargetState.GetDefault();
    }
}
