//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// <copyright file="StatsPoint.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

#nullable enable
using DatadogTestLogger.Vendors.Datadog.Trace.DataStreamsMonitoring.Hashes;

namespace DatadogTestLogger.Vendors.Datadog.Trace.DataStreamsMonitoring.Aggregation;

internal readonly struct StatsPoint
{
    public readonly string[] EdgeTags;
    public readonly PathwayHash Hash;
    public readonly PathwayHash ParentHash;
    public readonly long TimestampNs;
    public readonly long PathwayLatencyNs;
    public readonly long EdgeLatencyNs;

    public StatsPoint(
        string[] edgeTags,
        PathwayHash hash,
        PathwayHash parentHash,
        long timestampNs,
        long pathwayLatencyNs,
        long edgeLatencyNs)
    {
        EdgeTags = edgeTags;
        Hash = hash;
        ParentHash = parentHash;
        TimestampNs = timestampNs;
        PathwayLatencyNs = pathwayLatencyNs;
        EdgeLatencyNs = edgeLatencyNs;
    }
}
