//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032// <copyright file="CodeOwnersFileLocator.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>
#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using DatadogTestLogger.Vendors.Datadog.Trace.Logging;
using DatadogTestLogger.Vendors.Datadog.Trace.Util;

namespace DatadogTestLogger.Vendors.Datadog.Trace.Ci.CodeOwnership;

/// <summary>
/// Finds and loads the CODEOWNERS file that applies to the current repository.
/// </summary>
internal sealed class CodeOwnersFileLocator
{
    private static readonly IDatadogLogger Log = DatadogLogging.GetLoggerFor<CodeOwnersFileLocator>();

    internal CodeOwnersFileLocator(
        string? sourceRoot,
        string? workspacePath,
        string? repository,
        string? provider,
        string? localRepositoryRoot,
        string? localRepository)
    {
        var sourceDirectory = RepositorySourcePathResolver.GetSearchStart(sourceRoot, workspacePath);
        var workspaceDirectory = RepositorySourcePathResolver.GetSearchStart(workspacePath, basePath: null);
        var foundGitRoot = false;
        LocatedFile = TryLoadFromGitRoot(sourceDirectory, ref foundGitRoot, repository, provider)
                   ?? TryLoadFromGitRoot(workspaceDirectory, ref foundGitRoot, repository, provider)
                   ?? TryLoadFromGitRoot(
                          localRepositoryRoot,
                          ref foundGitRoot,
                          localRepository,
                          provider,
                          preferRepositoryLayout: true,
                          requireCodeOwnersAtHead: true);

        if (LocatedFile is null && !foundGitRoot)
        {
            LocatedFile = TryLoadFromExplicitRoot(workspaceDirectory, repository, provider)
                       ?? TryLoadFromExplicitRoot(sourceDirectory, repository, provider);
        }
    }

    /// <summary>
    /// Gets the CODEOWNERS file found when the test session was initialized.
    /// </summary>
    internal LocatedCodeOwners? LocatedFile { get; }

    private LocatedCodeOwners? TryLoadFromGitRoot(
        string? startDirectory,
        ref bool foundGitRoot,
        string? repository,
        string? provider,
        bool preferRepositoryLayout = false,
        bool requireCodeOwnersAtHead = false)
    {
        var repositoryRoot = FindGitRoot(startDirectory);
        if (repositoryRoot is null)
        {
            return null;
        }

        foundGitRoot = true;
        return TryLoadFromRepositoryRoot(repositoryRoot, repository, provider, preferRepositoryLayout, requireCodeOwnersAtHead);
    }

    private static string? FindGitRoot(string? startDirectory)
    {
        if (StringUtil.IsNullOrEmpty(startDirectory))
        {
            return null;
        }

        DirectoryInfo? directory;
        try
        {
            directory = new DirectoryInfo(startDirectory);
        }
        catch (Exception ex)
        {
            Log.Debug(ex, "Error resolving CODEOWNERS search directory from '{Path}'", startDirectory);
            return null;
        }

        while (directory is not null)
        {
            if (HasGitMarker(directory.FullName))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        return null;
    }

    private LocatedCodeOwners? TryLoadFromRepositoryRoot(
        string root,
        string? repository,
        string? provider,
        bool preferRepositoryLayout = false,
        bool requireCodeOwnersAtHead = false)
    {
        var dialect = DetectDialect(root, repository, provider, preferRepositoryLayout);
        var codeOwnersPath = requireCodeOwnersAtHead
                                 ? FindCodeOwnersPathAtHead(root, dialect)
                                 : FindCodeOwnersPath(root, dialect);
        if (codeOwnersPath is null)
        {
            return null;
        }

        Log.Information("CODEOWNERS file found: {Path}", codeOwnersPath);

        return CodeOwners.TryLoad(codeOwnersPath, dialect, out var rules)
                   ? new LocatedCodeOwners(rules, root)
                   : null;
    }

    private LocatedCodeOwners? TryLoadFromExplicitRoot(string? root, string? repository, string? provider)
        => StringUtil.IsNullOrEmpty(root) ? null : TryLoadFromRepositoryRoot(root, repository, provider);

    private static string? FindCodeOwnersPathAtHead(string repositoryRoot, CodeOwners.Dialect dialect)
    {
        try
        {
            // HEAD controls provider precedence even when a candidate was added or deleted locally.
            foreach (var path in GetCodeOwnersPaths(repositoryRoot, dialect))
            {
                var relativePath = GetRepositoryRelativePath(repositoryRoot, path);
                var result = AsyncUtil.RunSync(
                    () => ProcessHelpers.RunCommandAsync(
                        new ProcessHelpers.Command(
                            "git",
                            "rev-parse --verify HEAD:" + relativePath,
                            repositoryRoot)));
                if (result is { ExitCode: 0 } && result.Output.Length > 0)
                {
                    return IsFileAtHead(repositoryRoot, path, result.Output) ? path : null;
                }
            }
        }
        catch (Exception ex)
        {
            Log.Debug(ex, "Error finding local CODEOWNERS file in HEAD: {RepositoryRoot}", repositoryRoot);
        }

        return null;
    }

    private static bool IsFileAtHead(string repositoryRoot, string filePath, string headHash)
    {
        var relativePath = GetRepositoryRelativePath(repositoryRoot, filePath);
        try
        {
            var workingTreeHash = AsyncUtil.RunSync(
                () => ProcessHelpers.RunCommandAsync(
                    new ProcessHelpers.Command(
                        "git",
                        "hash-object --path=" + relativePath + " " + relativePath,
                        repositoryRoot)));
            return workingTreeHash is { ExitCode: 0 } &&
                   string.Equals(workingTreeHash.Output, headHash, StringComparison.OrdinalIgnoreCase);
        }
        catch (Exception ex)
        {
            Log.Debug(ex, "Error validating local CODEOWNERS file against HEAD: {Path}", filePath);
            return false;
        }
    }

    private static string GetRepositoryRelativePath(string repositoryRoot, string filePath)
    {
        var relativePathStart = repositoryRoot.Length;
        while (relativePathStart < filePath.Length &&
               (filePath[relativePathStart] == Path.DirectorySeparatorChar ||
                filePath[relativePathStart] == Path.AltDirectorySeparatorChar))
        {
            relativePathStart++;
        }

        return filePath.Substring(relativePathStart).Replace('\\', '/');
    }

    private static CodeOwners.Dialect DetectDialect(string root, string? repository, string? provider, bool preferRepositoryLayout)
    {
        var repositoryDialect = GetDialectFromRepository(repository);
        if (repositoryDialect.HasValue)
        {
            return repositoryDialect.Value;
        }

        if (preferRepositoryLayout)
        {
            var layoutDialect = GetDialectFromRepositoryLayout(root);
            if (layoutDialect.HasValue)
            {
                return layoutDialect.Value;
            }
        }

        if (string.Equals(provider, "gitlab", StringComparison.Ordinal))
        {
            return CodeOwners.Dialect.GitLab;
        }

        if (string.Equals(provider, "github", StringComparison.Ordinal))
        {
            return CodeOwners.Dialect.GitHub;
        }

        return GetDialectFromRepositoryLayout(root) ?? CodeOwners.Dialect.GitHub;
    }

    private static CodeOwners.Dialect? GetDialectFromRepositoryLayout(string root)
    {
        var hasGitHubCodeOwners = File.Exists(Path.Combine(root, ".github", "CODEOWNERS"));
        var hasGitLabCodeOwners = File.Exists(Path.Combine(root, ".gitlab", "CODEOWNERS"));
        if (hasGitHubCodeOwners == hasGitLabCodeOwners)
        {
            return null;
        }

        return hasGitLabCodeOwners ? CodeOwners.Dialect.GitLab : CodeOwners.Dialect.GitHub;
    }

#pragma warning disable SA1204
    private static CodeOwners.Dialect? GetDialectFromRepository(string? repository)
    {
        if (StringUtil.IsNullOrWhiteSpace(repository))
        {
            return null;
        }

        string? host = null;
        if (Uri.TryCreate(repository, UriKind.Absolute, out var repositoryUri) && !StringUtil.IsNullOrEmpty(repositoryUri.Host))
        {
            host = repositoryUri.Host;
        }
        else
        {
            // SCP-style SSH URLs look like git@gitlab.com:group/project.git.
            var hostStart = repository.IndexOf('@') + 1;
            var hostEnd = repository.IndexOf(':', hostStart);
            if (hostStart > 0 && hostEnd > hostStart)
            {
                host = repository.Substring(hostStart, hostEnd - hostStart);
            }
        }

        if (IsGitLabHost(host))
        {
            return CodeOwners.Dialect.GitLab;
        }

        if (string.Equals(host, "github.com", StringComparison.OrdinalIgnoreCase))
        {
            return CodeOwners.Dialect.GitHub;
        }

        return null;
    }

    private static bool IsGitLabHost(string? host)
        => string.Equals(host, "gitlab.com", StringComparison.OrdinalIgnoreCase) ||
           (host?.StartsWith("gitlab.", StringComparison.OrdinalIgnoreCase) ?? false) ||
           (host?.IndexOf(".gitlab.", StringComparison.OrdinalIgnoreCase) >= 0);

    private static bool HasGitMarker(string path)
    {
        var gitPath = Path.Combine(path, ".git");
        return Directory.Exists(gitPath) || File.Exists(gitPath);
    }

    private static string? FindCodeOwnersPath(string root, CodeOwners.Dialect dialect)
    {
        foreach (var path in GetCodeOwnersPaths(root, dialect))
        {
            if (File.Exists(path))
            {
                return path;
            }
        }

        return null;
    }

    /// <remarks>
    /// See <see href="https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location">GitHub CODEOWNERS file locations</see>
    /// and <see href="https://docs.gitlab.com/user/project/codeowners/#codeowners-file">GitLab CODEOWNERS file locations</see>.
    /// </remarks>
    private static IEnumerable<string> GetCodeOwnersPaths(string root, CodeOwners.Dialect dialect)
    {
        if (dialect == CodeOwners.Dialect.GitHub)
        {
            yield return Path.Combine(root, ".github", "CODEOWNERS");
            yield return Path.Combine(root, "CODEOWNERS");
            yield return Path.Combine(root, "docs", "CODEOWNERS");
        }
        else
        {
            yield return Path.Combine(root, "CODEOWNERS");
            yield return Path.Combine(root, "docs", "CODEOWNERS");
            yield return Path.Combine(root, ".gitlab", "CODEOWNERS");
        }
    }
#pragma warning restore SA1204

    internal sealed class LocatedCodeOwners
    {
        internal LocatedCodeOwners(CodeOwners rules, string repositoryRoot)
        {
            Rules = rules;
            RepositoryRoot = repositoryRoot;
        }

        internal CodeOwners Rules { get; }

        internal string RepositoryRoot { get; }
    }
}
